# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18WOBYlfjXX0hBeultL-lHa8X_9rgj22k
"""

from google.colab import files

import pandas as pd
import numpy as np

from sklearn.metrics import f1_score
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder



uploaded = files.upload()



train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
submission = pd.read_csv("sample_submission.csv")



X = train.drop(columns=["target", "id"])
y = train["target"]
X_test = test.drop(columns=["id"])



num_cols = ["age", "trestbps", "chol", "thalach", "oldpeak"]
cat_cols = ["sex", "cp", "fbs", "restecg", "exang", "slope", "ca", "thal"]



X_num = X[num_cols]
X_cat = X[cat_cols]
X_test_num = X_test[num_cols]
X_test_cat = X_test[cat_cols]



num_imp = SimpleImputer(strategy="median")
cat_imp = SimpleImputer(strategy="most_frequent")
X_num_imp = num_imp.fit_transform(X_num)
X_cat_imp = cat_imp.fit_transform(X_cat)
X_test_num_imp = num_imp.transform(X_test_num)
X_test_cat_imp = cat_imp.transform(X_test_cat)



ss = StandardScaler()
X_num_ss = ss.fit_transform(X_num_imp)
X_test_num_ss = ss.transform(X_test_num_imp)



ohe = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
X_cat_ohe = ohe.fit_transform(X_cat_imp)
X_test_cat_ohe = ohe.transform(X_test_cat_imp)

cat_ohe_cols = ohe.get_feature_names_out(cat_cols)



def make_df(num_arr, cat_arr, index):
    return pd.concat(
        [
            pd.DataFrame(num_arr, columns=num_cols, index=index),
            pd.DataFrame(cat_arr, columns=cat_ohe_cols, index=index)
        ],
        axis=1
    )

X_final = make_df(X_num_ss, X_cat_ohe, X.index)
X_test_final = make_df(X_test_num_ss, X_test_cat_ohe, X_test.index)



X_train, X_val, y_train, y_val = train_test_split(
    X_final, y, test_size=0.2, random_state=42, stratify=y
)



clf = LogisticRegression(max_iter=2000, random_state=42)
clf.fit(X_train, y_train)

train_pred = clf.predict(X_train)
print(f"[Train] F1: {f1_score(y_train, train_pred):.4f}")

val_pred = clf.predict(X_val)
print(f"[Validation] F1: {f1_score(y_val, val_pred):.4f}")



clf.fit(X_final, y)
test_pred = clf.predict(X_test_final)

submission["target"] = test_pred
submission.to_csv("submission.csv", index=False)

files.download("submission.csv")